version: "3.8"

services:
  app:
    build: .
    environment:
      - DEBUG=True
      - FLASK_DEBUG=True
      - SQLALCHEMY_TRACK_MODIFICATIONS=False
      - BASE_URL="localhost:5000"
      - EMAIL_HOST=
      - EMAIL_PORT=
      - EMAIL_SSL=
      - EMAIL_USER=
      - EMAIL_PASS=
      - EMAIL_FROM_ADDRESS=
    ports:
      - "5000:5000"
