version: "3.8"

services:
  app:
    build: .
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - DEBUG=
      - FLASK_DEBUG=
      - SQLALCHEMY_TRACK_MODIFICATIONS=
      - BASE_URL=localhost:5000
      - EMAIL_HOST=
      - EMAIL_PORT=
      - EMAIL_SSL=
      - EMAIL_USER=
      - EMAIL_PASS=
      - EMAIL_FROM_ADDRESS=
    ports:
      - "5000:5000"
