"""empty message

Revision ID: d457052fb3cf
Revises: 0c3757c3cf73
Create Date: 2019-11-15 00:18:22.567635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd457052fb3cf'
down_revision = '0c3757c3cf73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'rol', new_column_name='roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'roles', new_column_name='rol')
    # ### end Alembic commands ###
